services:
  - type: web
    name: mutant-detector
    env: java
    buildCommand: bash setup.sh
    startCommand: java -jar build/libs/mutant-detector-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk